version: '3.8'
services:
  mysql:
    image: mysql:8
    container_name: ecommerce-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce
    ports:
      - "3307:3306"
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./ecommerce-backend
    container_name: ecommerce-backend
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ecommerce
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  frontend:
    build: ./ecommerce-frontend
    container_name: ecommerce-frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
